<div class="btQuoteBooking this_is_extra_class btQuoteBookingWithColor c61dc823bf080b" data-admin_email="euroefect@mail.ru" data-cf7_id="14" data-email_client="yes" data-email_gdpr="" data-email_gdpr_text="" data-email_gdpr_not_text="" data-currency="$" data-currency_after="yes" data-currency_space="" data-url_confirmation="" data-url_ajax="https://translateget.com/wp-admin/admin-ajax.php" data-subject="" data-email_header="" data-email_footer="" data-date_text="Preferred Service Date" data-time_text="Preferred Service Time" data-message_please_wait="Please wait..." data-message_success="Thank you, we will contact you soon!" data-message_error="Error! Please try again later." data-message_mandatory="Please fill out all required fields." data-rec_secret_key="" data-total_text="Total" data-total_format="currency_1" data-total_decimals="1" data-date_format="" data-bt_cc_nonce="7a20000177" data-hide_total="" style="opacity: 1;"><div class="btQuoteBookingWrap"><div class="btQuoteBookingForm btActive"><div class="btQuoteMBlock"><div class="btQuoteItem " id="btQuoteItem61dc823bf0a4d"><label>Select Service</label>
		<div class="btQuoteItemInput"><div id="61dc823bf0c82W779" class="btQuoteSelect btContactField btDropDown btQuoteElement" data-condition="" data-initial-value="1"><div class="ddOutOfVision" id="msdropdown20_msddHolder" style="height: 0px; overflow: hidden; position: relative;"><select id="msdropdown20" name="61dc823bf0c82W779" style="width: 250px;"><option value="">Select...</option><option value="0.06" data-description="We will translate any document from English to German/Italian/Spanish/French and vice versa." data-image="">Any Document</option></select></div><div class="dd ddcommon borderRadius" id="msdropdown20_msdd" style=""><div class="ddTitle borderRadiusTp"><span class="divider"></span><span class="arrow arrowoff"></span><span class="ddTitleText" id="msdropdown20_title"><span class="ddlabel">Any Document<span class="description">We will translate any document from English to German/Italian/Spanish/French and vice versa.</span></span></span></div><input id="msdropdown20_titleText" type="text" autocomplete="off" class="text shadow borderRadius" style="display: none;"><div class="ddChild ddchild_ border shadow" id="msdropdown20_child" style="z-index: 1; display: none; position: relative; top: 56px;"><ul><li class="enabled _msddli_"><span class="ddlabel">Select...</span><div class="clear"></div></li><li class="enabled _msddli_ selected"><span class="ddlabel">Any Document<span class="description">We will translate any document from English to German/Italian/Spanish/French and vice versa.</span></span><div class="clear"></div></li></ul></div></div></div></div></div><div class="btQuoteItem " id="btQuoteItem61dc823bf0d55"><label>Number of words</label>
		<div class="btQuoteItemInput"><div class="btQuoteSlider btQuoteElement ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content" data-value="100" data-initial-value="100" data-min="1" data-max="20000" data-step="1" data-price="1" data-offset="0" data-condition=""><span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default" style="left: 23.7162%;"><span class="btQuoteSliderValue">4744</span></span></div></div></div></div><div class="btQuoteItem " id="btQuoteItem61dc823bf0e18"><label>Qty:</label>
		<div class="btQuoteItemInput"><input type="text" class="btQuoteText btQuoteElement" data-condition="" data-price="0" value="1" data-initial-value="1"></div></div><div class="btTotalNextWrapper"><div class="btQuoteTotal currencyAfter"><span class="btQuoteTotalText">Total</span><span class="btQuoteTotalCalc">284.6</span><span class="btQuoteTotalCurrency">$</span></div><div class="btPayPalButton" style="background-image:url(https://translateget.com/wp-content/plugins/bt_cost_calculator/paypal.png);"></div><form class="btPayPalForm" action="https://www.paypal.com/cgi-bin/webscr" method="post">
						<input type="hidden" name="cmd" value="_cart">
						<input type="hidden" name="upload" value="1">
						<input type="hidden" name="business" value="euroefect@mail.ru">
						<input type="hidden" name="item_name" value="Shop">
						<input type="hidden" name="currency_code" value="USD">
						<input type="image" src="https://translateget.com/wp-content/plugins/bt_cost_calculator/paypal.png" name="submit" alt="PayPal">
						<input type="hidden" name="item_name_1" value="Select Service: Any Document" class="btPayPalItem"><input type="hidden" name="amount_1" value="0.06" class="btPayPalItem"><input type="hidden" name="quantity_1" value="4744" class="btPayPalItem"></form></div></div></div></div>